import { ColorPalette, ThemeColors } from './types';

export const palette: ColorPalette = {
    orange: '#FF9B42',
    white: '#FFFFFF',
    black: '#000000',
    grey: {
        50: '#F9FAFB',
        100: '#F3F4F6',
        200: '#E5E7EB',
        300: '#D1D5DB',
        400: '#9CA3AF',
        500: '#6B7280',
        600: '#4B5563',
        700: '#374151',
        800: '#1F2937',
        900: '#111827',
    },
    red: '#E53935',
    green: '#10B981',
    blue: '#1E40AF',
    blueLight: '#DBEAFE',
    orangeLight: '#FFF8EE',
    transparent: 'transparent',
};

export const lightColors: ThemeColors = {
    primary: palette.orange,
    primaryLight: palette.orangeLight,
    background: '#F8F8F8',
    card: palette.white,
    text: '#333333',
    textSecondary: '#666666',
    textTertiary: '#999999',
    border: '#DDDDDD',
    error: palette.red,
    success: palette.green,
    info: palette.blue,
    infoLight: palette.blueLight,
    tint: palette.orange,
    tabIconDefault: '#CCCCCC',
    tabIconSelected: palette.orange,
    modalOverlay: 'rgba(0,0,0,0.5)',
    shadowColor: palette.black,
    warningText: '#92400E',
    white: palette.white,
};

export const darkColors: ThemeColors = {
    primary: palette.orange,
    primaryLight: 'rgba(255, 155, 66, 0.15)',
    background: palette.grey[900],
    card: palette.grey[800],
    text: palette.grey[100],
    textSecondary: palette.grey[400],
    textTertiary: palette.grey[500],
    border: palette.grey[700],
    error: '#EF4444',
    success: '#34D399',
    info: '#60A5FA',
    infoLight: 'rgba(30, 64, 175, 0.2)',
    tint: palette.orange,
    tabIconDefault: palette.grey[600],
    tabIconSelected: palette.orange,
    modalOverlay: 'rgba(0,0,0,0.7)',
    shadowColor: palette.black,
    warningText: '#FBBF24',
    white: palette.white,
};
