import { ColorPalette, ThemeColors } from './types';

export const palette: ColorPalette = {
    orange: '#FF9B42',
    orangeLight: '#FFF8EE',
    orangeDark: '#E88A35',
    cream: '#FFFAF0',
    white: '#FFFFFF',
    black: '#000000',
    grey: {
        50: '#F9FAFB',
        100: '#F3F4F6',
        200: '#E5E7EB',
        300: '#D1D5DB',
        400: '#9CA3AF',
        500: '#6B7280',
        600: '#4B5563',
        700: '#374151',
        800: '#1F2937',
        900: '#111827',
        950: '#0D1117',
    },
    red: '#E53935',
    redLight: '#FFEBEE',
    green: '#10B981',
    greenLight: '#E8F5E9',
    blue: '#1E40AF',
    blueLight: '#DBEAFE',
    yellow: '#F59E0B',
    yellowLight: '#FEF3C7',
    purple: '#9C27B0',
    purpleLight: '#F3E5F5',
    transparent: 'transparent',
};

export const lightColors: ThemeColors = {
    primary: palette.orange,
    primaryLight: palette.orangeLight,
    primaryDark: palette.orangeDark,
    background: palette.cream,
    backgroundSecondary: palette.grey[50],
    card: palette.white,
    cardElevated: palette.white,
    text: '#333333',
    textSecondary: '#666666',
    textTertiary: '#999999',
    textInverse: palette.white,
    border: '#EEEEEE',
    borderLight: '#F5F5F5',
    divider: '#F0F0F0',
    error: palette.red,
    errorLight: palette.redLight,
    success: palette.green,
    successLight: palette.greenLight,
    warning: palette.yellow,
    warningLight: palette.yellowLight,
    info: palette.blue,
    infoLight: palette.blueLight,
    tint: palette.orange,
    tabIconDefault: '#CCCCCC',
    tabIconSelected: palette.orange,
    modalOverlay: 'rgba(0,0,0,0.5)',
    shadowColor: palette.black,
    warningText: '#92400E',
    white: palette.white,
    skeleton: '#E5E7EB',
    skeletonHighlight: '#F3F4F6',
    inputBackground: palette.white,
    inputBorder: '#E5E7EB',
    inputPlaceholder: '#9CA3AF',
    buttonDisabled: '#E5E7EB',
    buttonDisabledText: '#9CA3AF',
    ripple: 'rgba(255, 155, 66, 0.15)',
    overlay: 'rgba(0, 0, 0, 0.4)',
    statusPreparing: palette.orange,
    statusReady: '#2196F3',
    statusDelivered: palette.green,
    statusCancelled: palette.red,
    statusScheduled: palette.grey[500],
};

export const darkColors: ThemeColors = {
    primary: palette.orange,
    primaryLight: 'rgba(255, 155, 66, 0.15)',
    primaryDark: '#FFB366',
    background: palette.grey[950],
    backgroundSecondary: palette.grey[900],
    card: palette.grey[800],
    cardElevated: palette.grey[700],
    text: palette.grey[100],
    textSecondary: palette.grey[400],
    textTertiary: palette.grey[500],
    textInverse: palette.grey[900],
    border: palette.grey[700],
    borderLight: palette.grey[800],
    divider: palette.grey[800],
    error: '#EF4444',
    errorLight: 'rgba(239, 68, 68, 0.15)',
    success: '#34D399',
    successLight: 'rgba(52, 211, 153, 0.15)',
    warning: '#FBBF24',
    warningLight: 'rgba(251, 191, 36, 0.15)',
    info: '#60A5FA',
    infoLight: 'rgba(96, 165, 250, 0.15)',
    tint: palette.orange,
    tabIconDefault: palette.grey[600],
    tabIconSelected: palette.orange,
    modalOverlay: 'rgba(0,0,0,0.7)',
    shadowColor: palette.black,
    warningText: '#FBBF24',
    white: palette.white,
    skeleton: palette.grey[700],
    skeletonHighlight: palette.grey[600],
    inputBackground: palette.grey[800],
    inputBorder: palette.grey[700],
    inputPlaceholder: palette.grey[500],
    buttonDisabled: palette.grey[700],
    buttonDisabledText: palette.grey[500],
    ripple: 'rgba(255, 155, 66, 0.2)',
    overlay: 'rgba(0, 0, 0, 0.6)',
    statusPreparing: palette.orange,
    statusReady: '#60A5FA',
    statusDelivered: '#34D399',
    statusCancelled: '#EF4444',
    statusScheduled: palette.grey[500],
};
